project_id = "yovjypyywcyfbhvcvnnp"

[functions.parse-transactions]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.wealth-analysis]
verify_jwt = false

[functions.wealth-wire]
verify_jwt = false
